AllCops:
  DisplayCopNames: true
  Exclude:
    - 'Gemfile'
    - 'bin/*'
    - 'config.ru'
    - 'config/spring.rb'
    - 'config/deploy.rb'
    - 'config/application.rb'
    - 'config/initializers/**/*'
    - 'config/environments/*'
    - 'db/fixtures/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'node_modules/**/*'
    - 'Rakefile'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'test/test_helper.rb'
    - 'test/channels/application_cable/connection_test.rb'
    - 'config/puma.rb'

Style/StringLiterals:
  Exclude:
    - 'bin/spring'
    - 'bin/yarn'
    - 'config/puma.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'app/models/application_record.rb'
    - 'app/channels/application_cable/connection.rb'
    - 'app/channels/application_cable/channel.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/jobs/application_job.rb'
    - 'config/**/*'
    - 'db/seeds.rb'

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/NumericPredicate:
  EnforcedStyle: comparison

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true
